apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetesSarang
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetesSarang
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetesSarang
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-kubernetesSarang
  template:
    metadata:
      labels:
        app: hello-kubernetesSarang
    spec:
      containers:
      - name: hello-kubernetesSarang
        image: paulbouwer/hello-kubernetes:1.7
        ports:
        - containerPort: 8080
